---
title: "Introduction to metaRmat"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to metaRmat}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r showdata, message = FALSE}
library(metaRmat)

becker09
```

```{r convert_data}
becker09_list <- df_to_corr(becker09, 
                            variables = c('Cognitive_Performance',
                                          'Somatic_Performance',
                                          'Selfconfidence_Performance', 
                                          'Somatic_Cognitive',
                                          'Selfconfidence_Cognitive',
                                          'Selfconfidence_Somatic'),
                            ID = 'ID')
```

## Calculate OS
```{r os}
olkin_siotani(becker09_list, becker09$N, type = 'simple')
olkin_siotani(becker09_list, becker09$N, type = 'average')
olkin_siotani(becker09_list, becker09$N, type = 'weighted')
```

# Master Prep Data Function
```{r prep_data}
input_metafor <- prep_data(becker09, becker09$N, type = 'weighted', 
          variable_names = c('Cognitive_Performance', 'Somatic_Performance',
                             'Selfconfidence_Performance', 
                             'Somatic_Cognitive',
                             'Selfconfidence_Cognitive',
                             'Selfconfidence_Somatic'),
          ID = 'ID')
fixed_model <- fit_model(data = input_metafor, effect_size = 'yi', 
          var_cor = 'V', moderators = ~ -1 + factor(outcome), 
          random_params = NULL)
random_model <- fit_model(data = input_metafor, effect_size = 'yi', 
          var_cor = 'V', moderators = ~ -1 + factor(outcome), 
          random_params = ~ factor(outcome) | factor(study))
```

# Extract model data
```{r extract_model_data}
model_out_fixed <- extract_model(fixed_model, 
                                 variable_names = c('Cognitive_Performance',
                                                    'Somatic_Performance',
                                                    'Selfconfidence_Performance', 
                                                    'Somatic_Cognitive',
                                                    'Selfconfidence_Cognitive',
                                                    'Selfconfidence_Somatic'))
model_out_random <- extract_model(random_model, 
                                  variable_names = c('Cognitive_Performance',
                                                     'Somatic_Performance',
                                                     'Selfconfidence_Performance', 
                                                     'Somatic_Cognitive',
                                                     'Selfconfidence_Cognitive',
                                                     'Selfconfidence_Somatic'))
```

# Fit model with lavaan
```{r model_lavaan}
model <- "## Regression paths
          Performance ~ Cognitive + Somatic + Selfconfidence
          Selfconfidence ~ Cognitive + Somatic
          ## Fix the variances of Cog and SO at 1
          Cognitive ~~ 1*Cognitive
          Somatic ~~ 1*Somatic
          Cognitive ~~ Somatic"

lavaan_output <- path_model(data = model_out_random, model = model, num_obs = 600)
summary(lavaan_output)
```

# Fit reduced model
```{r}
model <- "## Regression paths
          Performance ~ Cognitive + Somatic
          ## Fix the variances of Cog and SO at 1
          Cognitive ~~ 1*Cognitive
          Somatic ~~ 1*Somatic
          Cognitive ~~ Somatic"

lavaan_output <- path_model(data = model_out_random, model = "## Regression paths
          Performance ~ Cognitive + Somatic
          ## Fix the variances of Cog and SO at 1
          Cognitive ~~ 1*Cognitive
          Somatic ~~ 1*Somatic
          Cognitive ~~ Somatic", num_obs = 600)
summary(lavaan_output)
```


# Functions work with pipe `%>%`
```{r pipe, message = FALSE}
library(dplyr)

model <- "## Regression paths
          Performance ~ Cognitive + Somatic + Selfconfidence
          Selfconfidence ~ Cognitive + Somatic"

prep_data(becker09, becker09$N, type = 'weighted', 
          variable_names = c('Cognitive_Performance', 'Somatic_Performance',
                             'Selfconfidence_Performance', 
                             'Somatic_Cognitive',
                             'Selfconfidence_Cognitive',
                             'Selfconfidence_Somatic'),
          ID = 'ID') %>%
  fit_model(effect_size = 'yi', 
          var_cor = 'V', moderators = ~ -1 + factor(outcome), 
          random_params = ~ factor(outcome) | factor(study),
          structure = 'UN') %>%
  extract_model(variable_names = c('Cognitive_Performance',
                                   'Somatic_Performance',
                                   'Selfconfidence_Performance', 
                                   'Somatic_Cognitive',
                                   'Selfconfidence_Cognitive',
                                   'Selfconfidence_Somatic')) %>%
  path_model(model = model, num_obs = 600) %>% 
  summary()
```

